# ==========================
# Etapa 1 - Runtime
# ==========================
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

EXPOSE 8080
EXPOSE 8081

# ==========================
# Etapa 2 - Build
# ==========================
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

ARG BUILD_CONFIGURATION=Release

WORKDIR /src

COPY ["LibraryManager.API.csproj", "./"]

RUN dotnet restore "LibraryManager.API.csproj"

COPY . .

RUN dotnet build "LibraryManager.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# ==========================
# Etapa 3 - Publish
# ==========================
FROM build AS publish

ARG BUILD_CONFIGURATION=Release

RUN dotnet publish "LibraryManager.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# ==========================
# Etapa 4 - Final
# ==========================
FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "LibraryManager.API.dll"]